//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazarSodai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductsID { get; set; }
        public string ProducsName { get; set; }
        public Nullable<double> ProductsPrice { get; set; }
        public Nullable<double> ProductsWeight { get; set; }
        public string ProductsImage { get; set; }
        public Nullable<int> ProductsStock { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
